### ISSUE TITLE
Deployment of a PHP & mysql project doesn't work when the project name starts with a number

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#21]
No customization is needed to reproduce the issue - select PHP & Laravel, press create - it fails on stage deployment:

```
Traceback (most recent call last):
  File "/app/src/deploy/tasks.py", line 134, in async_deploy_bundle
    environment.services.ensure_provisioned()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/src/backing_services/managers.py", line 32, in ensure_provisioned
    self.iterator(), timeout=timeout
  File "/app/src/backing_services/utils.py", line 70, in ensure_services_provisioned
    raise ProvisioningFailed(service)
backing_services.exceptions.ProvisioningFailed: Provisioning of matomo-test / MySQL Database (US ECO (N.V., US)) (DEFAULT) failed because of an error
```

**Comment by viktor-yunenko** [comment]
Answer from the support:

> Hi Victor,
> Looks like our implementation of the MySQL service is a little bit too strict about database names, and requires them to start with a letter. The database name is generated from the project name, and yours starts with a digit. I'll try to make this check a bit more permissive, but I can't commit to any specific date when this change will make it live. In the mean time, choosing an application name starting with a letter should fix it for you.
> Apologies for the inconvenience, and have a nice evening!
> Michal

**Comment by kinkerl** [comment]
this is fixed @macolo
