### ISSUE TITLE
Could not translate host name "postgres" to address

### ISSUE THREAD

**Issue by vnosov93** [what-digital/divio#23]
```The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    startup.manage(path=os.path.dirname(os.path.abspath(__file__)))
  File "/usr/local/lib/python3.6/site-packages/aldryn_django/startup.py", line 12, in manage
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/cms/admin/__init__.py", line 11, in <module>
    plugin_pool.plugin_pool.discover_plugins()
  File "/usr/local/lib/python3.6/site-packages/cms/plugin_pool.py", line 43, in discover_plugins
    invalidate_cms_page_cache()
  File "/usr/local/lib/python3.6/site-packages/cms/cache/__init__.py", line 69, in invalidate_cms_page_cache
    version = _get_cache_version()
  File "/usr/local/lib/python3.6/site-packages/cms/cache/__init__.py", line 15, in _get_cache_version
 [sentry] DEBUG: Sending event, type:null level:error event_id:829bb3892ba14e57b72e6d8a4470aeae project:4077 host:app.getsentry.com
    version = cache.get(CMS_PAGE_CACHE_VERSION_KEY)
  File "/usr/local/lib/python3.6/site-packages/django/core/cache/backends/db.py", line 52, in get
    return self.get_many([key], version).get(key, default)
  File "/usr/local/lib/python3.6/site-packages/django/core/cache/backends/db.py", line 68, in get_many
    with connection.cursor() as cursor:
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution```

**Comment by viktor-yunenko** [comment]
The python error happens when aldryn-django config.py doesn't find the `DEFAULT_DB` env, it tries to use the one from `.env-local` as a fallback - `postgres://postgres@postgres:5432/db` - and fails since this is a docker container address.

The underlaying issue - absence of database that was supposed to be provided by the cloud - can have several causes.

**Comment by viktor-yunenko** [comment]
@vnosov93 , this issue isn't specified yet, please add the missing information.
