### ISSUE TITLE
aldryn-django doesn't support language dialects as de-ch or de-at

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#27]
We've been trying to workaround that issues during Sunday's night because we want to unblock the editors who have to start adding content now.

But workaround doesn't appear to be a reliable solution. It looks as something that needs to be fixed within aldryn-django.

To demonstrate the issue I created a test project on divio without any customization except. The only thing that I changed is the `LANGUAGES ` variable to `["de-ch", "de-at"]` - https://control.divio.com/control/1820/edit/86908/

![image](https://user-images.githubusercontent.com/36416236/88539217-84438a00-d019-11ea-972f-76044203aa05.png)

The error on deployment:
```
 ---> Running in 735a3b12a6f5
[91mTraceback (most recent call last):
  File "manage.py", line 7, in <module>
    startup.manage(path=os.path.dirname(os.path.abspath(__file__)))
  File "/usr/local/lib/python3.6/site-packages/aldryn_django/startup.py", line 12, in manage
[0m[91m    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
[0m[91m    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
[0m[91m    self._setup(name)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
[0m[91m    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
[0m[91m    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
[0m[91m    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[0m[91m  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[0m[91m  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[0m[91m  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[0m[91m  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[0m[91m  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[0m[91m  File "/app/settings.py", line 46, in <module>
[0m[91m    aldryn_addons.settings.load(locals())
[0m[91m  File "/usr/local/lib/python3.6/site-packages/aldryn_addons/settings.py", line 191, in load
[0m[91m    settings_json_path=settings_json_path,
  File "/usr/local/lib/python3.6/site-packages/aldryn_addons/settings.py", line 231, in load_addon_settings
[0m[91m    aldryn_config.Form().to_settings(addon_settings, settings),
  File "/app/addons/aldryn-django/aldryn_config.py", line 212, in to_settings
[0m[91m    self.i18n_settings(data, settings, env=env)
  File "/app/addons/aldryn-django/aldryn_config.py", line 488, in i18n_settings
[0m[91m    settings['LANGUAGES'] = language_codes_to_tuple(langs_from_form)
  File "/app/addons/aldryn-django/aldryn_config.py", line 477, in language_codes_to_tuple
[0m[91m    for code in codes
  File "/app/addons/aldryn-django/aldryn_config.py", line 477, in <listcomp>
[0m[91m    for code in codes
KeyError: 'de-ch'
[0m
```

**Comment by viktor-yunenko** [comment]
The error appears to be coming from - https://gitlab.com/what-digital/vertec-website/-/blob/master/addons/aldryn-django/aldryn_config.py#L476

**Comment by viktor-yunenko** [comment]
Hi @GaretJax, it doesn't look like I can do anything else about it, would you be able to assist with a fix for aldryn-django?

**Comment by GaretJax** [comment]
@victor-yunenko this does not seem to be an aldryn-django issue. The list of available languages comes from Django itself: https://github.com/django/django/blob/master/django/conf/global_settings.py#L51-L148

To fix your issue, define an appropriate `LANGUAGES` setting in `settings.py` before the aldryn django loading code, containing the languages you'd like to expose.

**Comment by viktor-yunenko** [comment]
Hi @GaretJax, I would say that it used to be both django and aldryn-django issue, but in 2015 django fixed the relaying on `global_settings.LANGUAGES`, therefore shouldn't aldryn-django adjust it as well? On a plain django project adding custom languages works normally, here I would say every developer would be running into that problem since divio docs advice to add settings after `aldryn_addons.settings.load(locals())`?
