### ISSUE TITLE
divio server migration to Swiss AZ region (Azure CH North) fails with storage errors

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#7]
Here's the latest error logs (with removed env secrets that for some reason are being printed out)

```
 ---> 98a6acc68381
Step 8/8 : ENV PYTHONUNBUFFERED=true
 ---> Running in 3d353e7ee67a
Removing intermediate container 3d353e7ee67a
 ---> faa51204ba6a
Successfully built faa51204ba6a
Successfully tagged app-registry-local.aldryn.net/{project_name}-live-0640aaa8646f4149b52e640adea48405.5eebef5c4aff47c18f62bcd6c4fd8dbd:bld-1ae4bc2804184defbf2af7580a9aeaca
finished docker build

===== docker build release =====

starting docker buildStep 1/2 : FROM app-registry-local.aldryn.net/{project_name}-live-0640aaa8646f4149b52e640adea48405.5eebef5c4aff47c18f62bcd6c4fd8dbd:bld-1ae4bc2804184defbf2af7580a9aeaca
 ---> faa51204ba6a
Step 2/2 : ENV BASE_URL=[...]
 ---> Running in bcab2fc501ba
Removing intermediate container bcab2fc501ba
 ---> 6f0cb1e69bba
Successfully built 6f0cb1e69bba
Successfully tagged app-registry-local.aldryn.net/{project_name}-live-0640aaa8646f4149b52e640adea48405.5eebef5c4aff47c18f62bcd6c4fd8dbd:rel-513fdccca1ee472993b7bbc3297769d7
finished docker build

===== docker migrate release =====
```

I guess the issue might be in the pending services attachment?

![image](https://user-images.githubusercontent.com/36416236/85317067-7359a300-b4c6-11ea-82ad-24d6f6f05363.png)

**Comment by viktor-yunenko** [comment]
After few hours the logs now contain an error:

```
===== docker migrate release =====

+ start migrate
Traceback (most recent call last):
  File "/usr/local/bin/aldryn-django", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/aldryn_django/cli.py", line 70, in main
    for key in dir(django_settings)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/settings.py", line 39, in <module>
    aldryn_addons.settings.load(locals())
  File "/usr/local/lib/python3.6/site-packages/aldryn_addons/settings.py", line 191, in load
    settings_json_path=settings_json_path,
  File "/usr/local/lib/python3.6/site-packages/aldryn_addons/settings.py", line 231, in load_addon_settings
    aldryn_config.Form().to_settings(addon_settings, settings),
  File "/app/addons/aldryn-django/aldryn_config.py", line 209, in to_settings
    self.storage_settings_for_media(settings, env=env)
  File "/app/addons/aldryn-django/aldryn_config.py", line 379, in storage_settings_for_media
    settings.update(parse_storage_url(settings['DEFAULT_STORAGE_DSN']))
  File "/usr/local/lib/python3.6/site-packages/aldryn_django/storage.py", line 129, in parse_storage_url
    config['DEFAULT_FILE_STORAGE'] = SCHEMES[scheme[0]]
KeyError: 'az'
Sentry is attempting to send 0 pending error messages
```

**Comment by viktor-yunenko** [comment]
And now a new one again:
```
Traceback (most recent call last):
  File "/app/src/deploy/tasks.py", line 143, in async_deploy_bundle
    migrate=migrate,
  File "/app/src/control/models.py", line 927, in deploy
    migrate=migrate,
  File "/app/src/deploy/base.py", line 174, in deploy
    src_env=copy_from, dst_env=self.environment
  File "/app/src/divio/services/applications/backing_services/utils.py", line 207, in copy_environment_services_data
    copy_services_data(matches)
  File "/app/src/divio/services/applications/backing_services/utils.py", line 102, in copy_services_data
    raise ServicesDataCopyFailure(copied, errors)
divio.services.applications.backing_services.utils.ServicesDataCopyFailure: ([(<ServiceInstance: {project_name} / PostgreSQL database (CH (Azure CH North)) (DEFAULT)>, <ServiceInstance: {project_name} / PostgreSQL database (CH (Azure CH North)) (DEFAULT)>)], [(<ServiceInstance: {project_name} / Object storage (CH (Azure CH North)) (DEFAULT)>, <ServiceInstance: {project_name} / Object storage (CH (Azure CH North)) (DEFAULT)>, RuntimeError('Backup restore failed. Error #None',))])
```

**Comment by viktor-yunenko** [comment]
The project was using the latest aldryn-django 2.2.13.1, but the only version that supports Swiss AZ region (run on Azure) is 2.2.12.2a3. After downgrading it and updating its config in `addons/` the deployment went normally.

**Comment by viktor-yunenko** [comment]
Hi @GaretJax, would it be ok to upgrade the azure projects to the latest version now?
